services:
  kong-migration:
    image: kong:3.7.0
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_DB_HOST}
      - KONG_PG_USER=${KONG_DB_USERNAME}
      - KONG_PG_PASSWORD=${KONG_DB_PASSWORD}
    command: "kong migrations bootstrap"
    networks:
      - kong-net
  kong:
    image: kong:3.7.0
    depends_on:
      - kong-migration
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_DB_HOST}
      - KONG_PG_USER=${KONG_DB_USERNAME}
      - KONG_PG_PASSWORD=${KONG_DB_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN}
      - KONG_ADMIN_GUI_URL=${KONG_ADMIN_GUI_URL}
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8444:8444
    networks:
      - kong-net

networks:
  kong-net: